//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDream.GUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GuiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuiStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eDream.GUI.GuiStrings", typeof(GuiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this dream entry?.
        /// </summary>
        internal static string EntryViewer_ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("EntryViewer_ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete entry?.
        /// </summary>
        internal static string EntryViewer_ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("EntryViewer_ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} is not a valid dream diary format or it has become corrupted..
        /// </summary>
        internal static string FrmMain_ShowLoadingErrorMessage {
            get {
                return ResourceManager.GetString("FrmMain_ShowLoadingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading the diary.
        /// </summary>
        internal static string FrmMain_ShowLoadingErrorTitle {
            get {
                return ResourceManager.GetString("FrmMain_ShowLoadingErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your dream entry doesn&apos;t have either a text or tags..
        /// </summary>
        internal static string NewEntryForm_SaveEdit_NoTextOrTagsMessage {
            get {
                return ResourceManager.GetString("NewEntryForm_SaveEdit_NoTextOrTagsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing dream information.
        /// </summary>
        internal static string NewEntryForm_SaveEdit_NoTextOrTagsTitle {
            get {
                return ResourceManager.GetString("NewEntryForm_SaveEdit_NoTextOrTagsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists. Do you wish to overwrite it?.
        /// </summary>
        internal static string NewFileBox_CreateButton_FileAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("NewFileBox_CreateButton_FileAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite file?.
        /// </summary>
        internal static string NewFileBox_CreateButton_FileAlreadyExistsTitle {
            get {
                return ResourceManager.GetString("NewFileBox_CreateButton_FileAlreadyExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name is not valid. It is using characters not allowed such as * . &quot; / \ [ ] : ; | = ,.
        /// </summary>
        internal static string NewFileBox_CreateButton_FileNameValidationErrorMessage {
            get {
                return ResourceManager.GetString("NewFileBox_CreateButton_FileNameValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name error.
        /// </summary>
        internal static string NewFileBox_CreateButton_FileNameValidationErrorTitle {
            get {
                return ResourceManager.GetString("NewFileBox_CreateButton_FileNameValidationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error saving your diary to {0}.
        /// </summary>
        internal static string SavingDiaryFailed_Message {
            get {
                return ResourceManager.GetString("SavingDiaryFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving your diary failed.
        /// </summary>
        internal static string SavingDiaryFailed_Title {
            get {
                return ResourceManager.GetString("SavingDiaryFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string Search_FromThisDate {
            get {
                return ResourceManager.GetString("Search_FromThisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this date.
        /// </summary>
        internal static string Search_OnThisDate {
            get {
                return ResourceManager.GetString("Search_OnThisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dream diary loaded.
        /// </summary>
        internal static string StatusBar_NoDreamDiaryLoaded {
            get {
                return ResourceManager.GetString("StatusBar_NoDreamDiaryLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dreams.
        /// </summary>
        internal static string StatusBarMessage_NoDreams {
            get {
                return ResourceManager.GetString("StatusBarMessage_NoDreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} in {2} {3} ({4:n2} dreams/day).
        /// </summary>
        internal static string StatusBarMessage_NumberDreamsAndDays {
            get {
                return ResourceManager.GetString("StatusBarMessage_NumberDreamsAndDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or whitespace..
        /// </summary>
        internal static string ValueCannotBeNullOrWhitespace {
            get {
                return ResourceManager.GetString("ValueCannotBeNullOrWhitespace", resourceCulture);
            }
        }
    }
}
